### ISSUE TITLE
Error: No available Cask for lumen

### ISSUE THREAD

**Issue by itsbrex** [anishathalye/lumen#12]
Can't figure out why this isn't working. Any ideas?

![image](https://cloud.githubusercontent.com/assets/9772694/17302647/109d2782-57d2-11e6-9a29-462e7cda00dd.png)

**Comment by anishathalye** [comment]
`brew cask update && brew cask install lumen`

**Comment by itsbrex** [comment]
hand --> face. 

Thanks!
