### ISSUE TITLE
Make menu bar icon bigger

### ISSUE THREAD

**Issue by jaredreich** [anishathalye/lumen#13]
It looks very out of place compared to all other application icons.

<img width="136" alt="screen shot 2016-08-01 at 9 02 49 pm" src="https://cloud.githubusercontent.com/assets/8563847/17315671/e7d77560-582a-11e6-8de6-3c3aecacf330.png">

**Comment by anishathalye** [comment]
Valid criticism. Anyone wanna send a PR?

(otherwise, I'll get to it eventually)

**Comment by jaredreich** [comment]
Also, I forgot to add, great work on Lumen!

**Comment by dialex** [comment]
Also it looks a lot like flux
![screen shot 2016-08-08 at 09 13 40](https://cloud.githubusercontent.com/assets/2140450/17473442/6e3fe494-5d48-11e6-976f-61cf5d381b8c.png)

**Comment by anishathalye** [comment]
Fixed in #30.
