### ISSUE TITLE
Doesn't appear to work on Sierra (10.12 b4)

### ISSUE THREAD

**Issue by BrianGilbert** [anishathalye/lumen#14]
I'm not seeing any changes in screen brightness, is there any way for me to debug this more?

**Comment by austin-millan** [comment]
@BrianGilbert,
I didn't notice a difference at first when I first downloaded Lumen. Did you try modifying the brightness (manually) for contents with varying luminosity? That should jumpstart code (found [here](https://github.com/anishathalye/lumen/blob/master/Lumen/BrightnessController.m#L73)) that checks if you've manually changed the brightness for the contents of the screen previously. If true, it will change the brightness accordingly depending on your past behavior.

**Comment by anishathalye** [comment]
What's your hardware setup? Currently, I've only tested it with a laptop with its built-in display (also, see #6).

Also, try this:
1. Start Lumen
2. Open up a dark window (e.g. a terminal) and make your display bright according to your preferences
3. Wait a second
4. Open up a light window (e.g. a web browser) and make your display darker according to your preferences
5. Wait a second

Now try switching back and forth between the two, and you should see it automatically doing stuff.

**Comment by BrianGilbert** [comment]
PEBKAC, I didn't realise you had to set the brightness manually.. thanks..

**Comment by nikolay** [comment]
@anishathalye So, we should turn automatic brightness off?

**Comment by anishathalye** [comment]
Correct
