### ISSUE TITLE
different transition time based on user action

### ISSUE THREAD

**Issue by andreineculau** [anishathalye/lumen#16]
on the line of #11 but still a different issue, I am getting headaches watching videos, or just scrolling web pages. When I switch between the browser (white pages) and my terminal (black background), I expect the brightness transition, but when I just scroll, or even don't do anything (video playing), I expect the transition to happen over a longer period of time, if any actually.

My suggestion would be to detect clicks (only main/left button) and keypresses (ignore dead keys) and only then treat the transitioning as normal. Otherwise, treat the transitioning as slowed down.

**Comment by anishathalye** [comment]
Yeah, that's a good idea. It probably makes the most sense to just stop the transitioning when you're watching videos, etc.

Not sure what's the best way to detect that, though.

**Comment by andreineculau** [comment]
As a intermediate solution, I'd be fine with just detecting if the focused (active application) changes. If it doesn't, then don't touch the brightness.

**Comment by austincondiff** [comment]
Or you could just increase the transition time to 2-5 seconds so that it is a little more seamless.

**Comment by anishathalye** [comment]
Closing due to age / inactivity.
