### ISSUE TITLE
minor: not everyone's terminal is dark

### ISSUE THREAD

**Issue by olets** [anishathalye/lumen#17]
What a cool tool! Have to say it was immediately odd to me that the readme assumes a dark terminal background.

**Comment by anishathalye** [comment]
From the readme:

> a dark window (for example, a full-screen terminal)

It does say "for example".

In the demo section:

> Without Lumen, web pages are too bright, and the terminal is too dark to read. With Lumen, it's perfect.

Well, it's showing my desktop, where I do have a dark terminal. I don't think it's necessary to be overly explicit and say "a dark window (e.g. my terminal setup, which currently has a dark theme)".

Though if you have suggestions, feel free to share.

**Comment by olets** [comment]
I guess I'd just say "a dark window." and "light windows are too bright, and dark windows are too dark." Or "(for example, my…)" and "and my terminal…"

Clearly a minor thing, go with what works for you. I do really like the comparison animation

**Comment by anishathalye** [comment]
Okay I'm just going to leave it the way it is for now.
