### ISSUE TITLE
Sleep / Temporary Stop

### ISSUE THREAD

**Issue by shaneargo** [anishathalye/lumen#19]
It'd be great to have the option to disable lumen for a limited period of time. An example of this is the application flux, which can be disabled for an hour, until sunrise (this could just be until some specific point in time) or for the life of the current app.

The main reason why this would be useful is sometimes you do not want to auto-adjusting of the brightness to occur, such as when you are watching a video. While lumen can be disabled during these times, I often forget to reenable it.

**Comment by anishathalye** [comment]
Good idea!

**Comment by ajorgensen** [comment]
In the same vein it would be awesome to be able to blacklist certain windows from lumen. An example would be watching a netflix show in another tab or browser window, when switching to the video lumen continually adjusts the brightness but I still want it to work for other windows.

**Comment by anishathalye** [comment]
Closing due to age / inactivity.
