### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by austincondiff** [anishathalye/lumen#20]
Lumen does not adjust in real time often blinding me when changing to a bright screen for half a second. Then when I switch to a dark screen it takes the same time to see it.

Please add a setting to adjust refresh rate.

**Comment by anishathalye** [comment]
Yeah… right now, it's hard-coded in https://github.com/anishathalye/lumen/blob/master/Lumen/Constants.h#L11

Making it too fast consumes too much CPU.

How should a setting be exposed to the user? (and is this too low-level to expose?)

**Comment by okayzed** [comment]
@anish: i think you can resolve part of this issue for already seen windows by recording the prior brightness values by window title or PID and restoring the brightness immediately when the window is re-focused.  the polling for window change could be done at a higher rate (say every 50 or 100ms), while the interval for the re-calibrate can be left at 500ms. 

this leaves only the case of newly seen windows being blinding for 500ms, but hopefully that happens less than 10% of the time.

**Comment by anish** [comment]
@okayzed wrong person

**Comment by okayzed** [comment]
@anish was an error, but let us rejoice that our paths crossed and we came to exchange letters, however briefly, and may you find yourself well in the future

**Comment by anishathalye** [comment]
@okayzed yeah, that's a good idea! related to #1

**Comment by Etheryte** [comment]
Perhaps there are additional heuristics that can be used as indicators for a recalculation? For example, mouse clicks would be a good cue that a recheck may be in order, though I'm not sure if there's a good cheap way to monitor that.

**Comment by anishathalye** [comment]
Closing due to age / inactivity.
