### ISSUE TITLE
Add option to disable Lumen for specific apps

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/lumen#21]
> In the same vein it would be awesome to be able to blacklist certain windows from lumen. An example would be watching a netflix show in another tab or browser window, when switching to the video lumen continually adjusts the brightness but I still want it to work for other windows.

(by @ajorgensen, via https://github.com/anishathalye/lumen/issues/19#issuecomment-240608988)

**Comment by ajorgensen** [comment]
Thanks for transferring this to a new issue, really enjoying using lumen!

**Comment by anishathalye** [comment]
Implemented in #24 :tada:
