### ISSUE TITLE
Lumen stops working when the computer goes to sleep

### ISSUE THREAD

**Issue by RIanDeLaCruz** [anishathalye/lumen#22]
When I leave my laptop to sleep, Lumen stops working when I wake up my laptop

**Comment by anishathalye** [comment]
Hmm, I tried it on my laptop and I couldn't reproduce the issue. It still works for me when I close the lid, let the computer sleep, and reopen the lid.

**Comment by anishathalye** [comment]
Cannot reproduce, going to close for now. Let me know if there's any new information.
