### ISSUE TITLE
[feature request] add ability to schedule the app

### ISSUE THREAD

**Issue by nikivdev** [anishathalye/lumen#23]
I really love the idea of the app and started using it but since it takes ~ 0.5 / 1 % of my CPU when using it, I'd like to deactivate it during day time and activate it again automatically in the evening?

Can you add the ability to set a schedule for it? Thank you.

**Comment by anishathalye** [comment]
Great idea!

**Comment by anishathalye** [comment]
(It would also be nice if we figured out how to reduce the CPU usage)

**Comment by anishathalye** [comment]
Closing due to age / inactivity.
