### ISSUE TITLE
lumen v 1.2.2 stops changing brightness and forgets settings when computer sleeps

### ISSUE THREAD

**Issue by gkrawiec** [anishathalye/lumen#32]
On the new release whenever computer goes to sleep and then wakes up I have to set the brightness manually once again as it seems to have lost the previous settings.
I use MacOS 11.1 and this can be reproduced by setting a high and a low brightness, forcing the machine to sleep and waking it up a few seconds later.

Let me know if you need any other information.

thanks.

**Comment by anishathalye** [comment]
Closing due to age / inactivity.
