### ISSUE TITLE
No Cask with this name exists.

### ISSUE THREAD

**Issue by fallinginenigma** [anishathalye/lumen#33]
When we try to install lumen, it says No Cask with this name exists.

![image](https://user-images.githubusercontent.com/56526091/121071174-3ed11b00-c7ed-11eb-8902-51ac46de69fe.png)

Thanks in advance.

**Comment by anishathalye** [comment]
That's weird. This exists: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/lumen.rb

And `brew install --cask lumen` works on my machine. Maybe you need a `brew update` or something? Can you install other casks?

**Comment by fallinginenigma** [comment]
I was able to install `brew install gcc` and brew is already up-to-date. I still couldn't get to install. Same error.

**Comment by anishathalye** [comment]
Can you `brew install --cask` anything else? Is your brew broken in any other way? See https://github.com/Homebrew/homebrew-cask/issues/71221 and issues linked in there. I don't think this is an issue with `lumen.rb`.

As a workaround, you can download a release from https://github.com/anishathalye/lumen/releases

**Comment by fallinginenigma** [comment]
There is definitely no issue with `lumen.rb`, something is wrong with `brew` itself. When I ran `brew update` it showed me a list with casks and I couldn't see lumen in the list. Unfortunately, I couldn't take a screenshot. 

Brew aside, how can I install the release using the terminal?

**Comment by anishathalye** [comment]
Yeah, I just tried it with a fresh install of macOS and Brew, and it works:

<img width="682" alt="Screen Shot 2021-06-22 at 7 04 57 AM" src="https://user-images.githubusercontent.com/3526486/122917874-7fbc4a00-d32c-11eb-88ec-af75cc7182ca.png">

You could try `brew doctor` to see if that fixes your brew installation; you could also try asking for help in the Brew issue tracker or [discussions](https://github.com/Homebrew/discussions/discussions).

You can also follow the [manual installation](https://github.com/anishathalye/lumen#download) instructions.

**Comment by anishathalye** [comment]
Closing because I think this should be resolved / is not a problem with lumen but with brew. Feel free to re-open if there's anything more.
