### ISSUE TITLE
macOS 11.5.1 m1 MBP 2020 - doesn't seem to work

### ISSUE THREAD

**Issue by anijatsu** [anishathalye/lumen#35]
The application opens, asks for the Screen Recording permission, restarts, and doesn't adjust the brightness no matter what I'm doing.

e.g. I switch to a dark mode website - set the brightness to high, go to a blank white page - set the brightness to lowest; then go back and see if the brightness changes via Lumen.

What debug information could I provide?

My only guess is this line I'm getting in Console:
`
error	14:51:16.495127+0200	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for accessing={identifier=com.anishathalye.Lumen, pid=33567, auid=501, euid=501, binary_path=/Applications/Lumen.app/Contents/MacOS/Lumen}, requesting={identifier=com.apple.appleeventsd, pid=466, auid=55, euid=55, binary_path=/System/Library/CoreServices/appleeventsd},
`

and this one as well:
`
error	14:39:03.289526+0200	Lumen	+[MTLIOAccelDevice registerDevices]: Zero Metal services found
`

**Comment by cad0p** [comment]
It doesn't seem to work for me as well unfortunately

here is what i found on my console (2021 MPB "14)

""" [app<application.com.anishathalye.Lumen.2946096.2946105(501)>:23481] Ignoring jetsam update because this process is not memory-managed """

**Comment by kimprap** [comment]
Any updates on this? Seems like it is not working with Apple Silicon cpus.

**Comment by anishathalye** [comment]
I still don't own an Apple Silicon laptop, so I can't test/debug this at the moment. I hope to be upgrading my laptop soon, though.

**Comment by ilgaur** [comment]
@anishathalye Are there any updates regarding the new laptop?

**Comment by anishathalye** [comment]
I do have an Apple Silicon laptop now; I think updating the software to work on the latest macOS will be a substantial amount of effort, requiring changing the way we capture screenshots, using [ScreenCaptureKit](https://developer.apple.com/documentation/screencapturekit/capturing-screen-content-in-macos?language=objc), and also changing the way we control the screen brightness.

It's not high priority for me right now to fix this software; happy to accept a PR, otherwise I might get around to this eventually.

**Comment by ivan-zakharchuk** [comment]
also not working for me on M1, great software idea though. I would be glad if someone would be able to fix it.

**Comment by anishathalye** [comment]
Using https://github.com/anishathalye/lumen/issues/37 as the master issue to track making Lumen compatible with the latest macOS and Apple Silicon.
