### ISSUE TITLE
Not able to install Lumen on Big Sur

### ISSUE THREAD

**Issue by rushiagr** [anishathalye/lumen#36]
Installed via `brew install --cask lumen`, and when I tried to open Lumen after typing it in Spotlight, getting the following popup, with no way to proceed further, and can just click 'OK'. 

```

“Lumen” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

Homebrew Cask downloaded this file today at 10:21 AM from github.com.

```

**Comment by anishathalye** [comment]
See the last line in this section: https://github.com/anishathalye/lumen#download; you can use [this technique](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) to open unsigned binaries.

**Comment by anishathalye** [comment]
You can also pass the `--no-quarantine` flag to brew when installing Lumen, i.e. `brew install --cask --no-quarantine lumen`.

**Comment by rushiagr** [comment]
Thanks! The brew install method worked for me. Maybe add it to the README as well?

**Comment by anishathalye** [comment]
Yes, already done in https://github.com/anishathalye/lumen/commit/7039d1bd5832933111f0c5baaef2be6a693e9584.
