### ISSUE TITLE
Brew formulae

### ISSUE THREAD

**Issue by jackturnbull** [anishathalye/lumen#5]
This may also solve https://github.com/anishathalye/lumen/issues/3, in that you won't need to provide auto-update functionality rather updates would be provided by brew.

If you want to submit the package to brew itself: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md

If you'd prefer to maintain your own tap:
https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

Never done one myself so not too confident about how to do it but happy to help with the process and testing where possible!

**Comment by anishathalye** [comment]
Great idea!

It would probably make the most sense to [add a cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md), right?

**Comment by chrisidefix** [comment]
If you want to deploy as an app-bundle instead of a commandline utility, a cask is the way to go, yes :) !

**Comment by anishathalye** [comment]
Wohoo, it's been added to Homebrew Cask.

Updated instructions in 8d2e6013d0fe075c0233c8a0cc741ee2e4efd81f.

**Comment by jackturnbull** [comment]
Nice work, thanks 😄
