### ISSUE TITLE
Add support for external monitors / multiple monitors

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/lumen#6]
According to [this comment](https://news.ycombinator.com/item?id=12196124) on HN, it seems that Lumen doesn't currently work properly with external monitors / multiple monitors.

**Comment by chrisidefix** [comment]
Would it be difficult to have separate brightness settings change dynamically for multiple monitors?

I assume this may only be possible through profiles, similar to what flux does?

Generally, it's likely that I may have a browser open on one screen and a terminal on the other. Of course knowing which app is active would help assuming which monitor I am looking at, but if I switch back to the terminal and all brightness increases again (and not just the terminal monitor), I'm still being blinded by the bright browser page :)

**Comment by chrisidefix** [comment]
PS: if this is implemented I assume this won't work in parallel with flux, so it would probably be wise to incorporate that functionality, unless Apple is already providing NightShift in the next update?

**Comment by chrisidefix** [comment]
I guess you'll have the same problem on a single split-screen monitor. If you have terminal or your editor and Safari open next to each other, which I often do... I don't see how this one can be solved with brightness, but let'a face it the main culprit is going to be the browser, right? So maybe we need a browser plugin that could communicate with the menubar app?

**Comment by anishathalye** [comment]
Hmm, yeah, this issue is somewhat complicated. I'm not sure what is the best way to do the design.

It would be nice if we could preserve the simplicity of the current interface.

**Comment by saxbophone** [comment]
+1

**Comment by madmod** [comment]
There are OS X apps like Nocturne which changes the color of the entire screen. Also Apple's assistive technologies filters. Maybe one of those techniques could be used?

**Comment by loginx** [comment]
There are applications that provide pseudo support for brightness adjustment of external monitors on mac os. They work by implementing a translucent overlay and letting you adjust the opacity.

One issue all of those applications have in common though, is that if you are frequently switching between the built-in panel and your external monitor, the overlay never properly adjusts to the new size of the display, so you end up with only a small part of your screen shaded. Invariably, you have to stop and restart the app.

I figured I'd bring this up here, so the devs keep in mind that the display can be resized during an active session, and the app should attempt to detect that and resize the overlays accordingly.

**Comment by MentalGear** [comment]
Yeah, I'm an an external monitor and Lumen doesn't work on 10.11. Would have loved to use it!

**Comment by craiglyons** [comment]
+1

**Comment by MentalGear** [comment]
anytime soon ?

**Comment by anishathalye** [comment]
I probably won't have time to work on this in the immediate future. If anyone wants to submit a pull request, that would be awesome. The code base is quite simple, so modifying it shouldn't be too bad.

**Comment by jbutz** [comment]
This may have been implied thus far, but being able to have independent brightness preferences for different monitors as indicated [here](http://www.anishathalye.com/2016/07/31/lumen/#configuration) would be an amazing part of this. I use my macbook's display, a thunderbolt display, and a dell monitor all together and different brightness on different screens is generally the way I work.

**Comment by anishathalye** [comment]
So… I don't have an external monitor, so it's kinda hard for me to implement this feature. But if anyone wants to buy me an external monitor where you can control the backlight, I'll implement this feature 😛

**Comment by MentalGear** [comment]
Hey, there. Could we maybe work together trying to implement this feature? It's quite crucial for a lot of people.

**Comment by anishathalye** [comment]
Sure! I'm happy to provide guidance / support / whatever, but it's hard for me to work on the code myself (because I still don't have a fancy external monitor)

**Comment by michaelsilver** [comment]
I've been manually disabling Lumen when I'm using an external monitor, so another option would be to automatically disable Lumen when an external display is detected. I found a solution to check this [using Swift](http://stackoverflow.com/questions/37189263/determine-external-screen-connected-to-the-macbook-computer-using-nsscreen) (I think), but I bet something similar could be done in Objective-C.

**Comment by anishathalye** [comment]
That seems like a good approach for now. Are you interested in implementing that functionality?

**Comment by ronakg** [comment]
Lumen works nicely with Lunar. Lumen adjusts the brightness of the laptop screen according to what's on the screen and Lunar keeps the monitor and laptop screens in sync.

**Comment by anishathalye** [comment]
@ronakg That's good to know! You're talking about https://lunar.fyi/, right? I should add a mention to the README. I can't test Lunar myself, because i don't have external monitors that support DDC. Is any extra setup needed to make it work with Lumen, or does it just work out of the box?

**Comment by ronakg** [comment]
> @ronakg That's good to know! You're talking about https://lunar.fyi/, right? I should add a mention to the README. I can't test Lunar myself, because i don't have external monitors that support DDC. Is any extra setup needed to make it work with Lumen, or does it just work out of the box?

Yes, that's the Lunar I'm talking about. There's no additional setup required, it works out of the box. Lumen changes the brightness of the laptop screen and Lunar keeps the external monitor brightness in sync with the laptop screen. How frequently Lunar syncs with the laptop screen can be configured in Lunar's preferences.

**Comment by forivall** [comment]
Hmm, I'm wondering if it works with [monitorcontrol.app](https://github.com/MonitorControl/MonitorControl). Some kind of hook between monitorcontrol and lumen would do the trick.

**Comment by anishathalye** [comment]
Closing due to age / inactivity.
