### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/lumen#7]
A bunch of people have been asking for a Linux port, so here's an issue where that can be discussed

**Comment by catskul** [comment]
Can probably use the same trick redshift does to make this work for linux:

https://github.com/jonls/redshift

... and/or add this functionality to redshift.

**Comment by meh** [comment]
@catskul redshift changes the gamma of the screen, it doesn't touch the backlight.

**Comment by StephanMeijer** [comment]
I'd like to see a Linux port. I might build an alternative for Linux myself.

**Comment by StephanMeijer** [comment]
@meh This issue confirms your claim: https://github.com/jonls/redshift/issues/125

**Comment by Enzime** [comment]
Take a look at the source of https://github.com/haikarainen/light

It sets the backlighting without an Xorg server being a requirement :)

**Comment by meh** [comment]
@StephanMeijer yeah I started working on a Linux alternative myself, with support for XRandr and the sysfs interface.

Mostly because I also want the adaption to take into consideration the current virtual desktop, and I think performance can be improved by avoiding polling and reacting to virtual desktop and window map/unmap changes.

**Comment by anishathalye** [comment]
Having someone else build a Linux alternative would be awesome 😄

**Comment by anishathalye** [comment]
Not sure about the current state of this project, but [autolux](https://github.com/okayzed/autolux) by @okayzed looks cool

**Comment by bencevans** [comment]
I've been building the required modules:
- [screenshot-desktop](https://github.com/bencevans/screenshot-desktop) to grab a screenshot - cross platform
- [pixel-average](https://github.com/bencevans/pixel-average) to measure image/content brightness

Come across the following useful modules:
- [brightness](https://github.com/kevva/brightness#readme) cross platform brightness manipulation
- [active-win](https://github.com/sindresorhus/active-win) detects current window. For this to be smooth we need to detect when a window changes and emit an event. Any help would be appreciated on https://github.com/sindresorhus/active-win/issues/1

With a spot of Electron I think we can get together a menu-bar app and package for OSX, Linux & Windows!

I've started a project with a very basic timer based brightness update ... https://github.com/bencevans/lumenaire

**Comment by anishathalye** [comment]
Oh, cool!

FYI, Electron apps [can be kinda resource intensive](https://github.com/anishathalye/lumen/issues/8#issuecomment-236733461), so that's something to watch out for.

**Comment by bencevans** [comment]
@anishathalye I believe that's down to how they're actually written. [Lumenaire](https://github.com/bencevans/lumenaire) is idling at 0/1% CPU currently and bursts to a max of 8% on my machine when an app changes and it's taking the snapshot, processing content brightness and updating screen brightness which doesn't seem to affect any performance :smile_cat:

**Comment by okayzed** [comment]
i would like to see a linux port of lumen, as well. 

i did some timing (to get a sense of performance) and here are my numbers (for 1920x1080 screen):

* import root window with imagemagick: takes 100ms +/- 20ms. 
* analyze average pixel intensity (using convert): dependent on size of input, but 10 - 50ms

for lower bound on timing:
* dump framebuffer using cat: 40ms (cat /dev/fb0) into 8MB raw file
* swap and rotate layers and downsize 8MB file: 20 - 60ms (using convert)

i don't think these numbers have a big performance impact on a system when run once every second or two (especially with multi cores). the main performance hit that i notice is a small stutter when xbacklight fades the screen display (if my mouse is moving, it is detectable).

**Comment by meh** [comment]
@okayzed I'm working on a native port that should improve performance and whatnot, it doesn't use external programs.

The repository is [here](https://github.com/meh/dux) but right now I just implemented backlight getting/setting, I'm working on the adaptive part right now.

**Comment by anishathalye** [comment]
@okayzed @bencevans added your projects to the list of [related projects](https://github.com/anishathalye/lumen#related-projects)

We can add [meh/dux](https://github.com/meh/dux) as well once it implements automatic backlight control

**Comment by meh** [comment]
Adaptive brightness is up, and released the crate on crates.io.

Different from what the other projects are doing:
- it doesn't use external commands
- it uses the MIT-SHM extension to fetch the screen content, which means no protocol overhead for the display
- it uses the DAMAGE extension to only fetch and recalculate the areas that actually changed on the screen (which reduces the overhead by a long shot)
- it also supports active window and active desktop based brightness on top of the luminance one

**Comment by anishathalye** [comment]
Whoa, that's cool! I've added a link in the readme of this repo.

**Comment by anishathalye** [comment]
Closing this issue because there are bunch of linux apps now!
