### ISSUE TITLE
Faster / no fade effect

### ISSUE THREAD

**Issue by balaclark** [anishathalye/lumen#9]
This tool is great, thanks! My only qualm is that you get a flash of brightness due to the fade effect of the brightness change, any chance to make the change instant / faster?

**Comment by anishathalye** [comment]
Hmm, so Lumen isn't doing any smooth transitions on purpose. I'm just doing:

``` objective-c
IODisplaySetFloatParameter(service, kNilOptions, CFSTR(kIODisplayBrightnessKey), level);
```

Other people have [asked about disabling brightness fading](http://apple.stackexchange.com/questions/235944/disable-smooth-fading-when-changing-brightness-of-macbook-pro-screen) on Stack Exchange, but there are no answers there.

I don't know if it's possible.

**Comment by anishathalye** [comment]
(I think it's more of a "cantfix" than a "wontfix")

**Comment by balaclark** [comment]
OK, thanks for looking into it!
